#!/bin/bash
#
# /etc/init.d/named
#
# chkconfig: 345 55 25
# description: BIND DNS server
# processname: named
# config: /etc/named.conf
# pidfile: /var/run/named/named.pid

### BEGIN INIT INFO
# Provides:          named
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Start/stop the BIND DNS server
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Variables
NAME=named
DAEMON=/usr/sbin/named
OPTIONS="-u named -c /etc/named.conf"
PIDFILE=/var/run/named/named.pid

start() {
    echo -n "Starting $NAME: "
    if [ -f $PIDFILE ] && pidofproc -p $PIDFILE $DAEMON > /dev/null; then
        echo "already running."
        return 0
    fi
    mkdir -p /var/run/named
    chown named:named /var/run/named
    daemon --pidfile=$PIDFILE $DAEMON $OPTIONS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$NAME
    return $RETVAL
}

stop() {
    echo -n "Stopping $NAME: "
    killproc -p $PIDFILE $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$NAME $PIDFILE
    return $RETVAL
}

status_named() {
    status -p $PIDFILE $DAEMON
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status_named
        ;;
    restart|reload|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
exit 0
